### ISSUE TITLE
File won't open.

### ISSUE THREAD

**Issue by BoggyDG** [MauveCloud/Ic2ExpReactorPlanner#10]
Yes, i do have java, no, i'm not stupid, yes, i did try to double-click it. It just loads for a fraction of a second and nothing happens. maybe it's because i have windows 10, but idk.

**Comment by MauveCloud** [comment]
Hopefully fixed in v2.1.3.

**Comment by MauveCloud** [comment]
In case others see this, BoggyDG provided more details in this thread: https://forum.industrial-craft.net/thread/12003-the-reactor-planner-won-t-open/ and I have more recently discovered that it was related to a JDK bug: https://bugs.openjdk.java.net/browse/JDK-8139507

The fix (for the planner) involved removing usage of Preferences.userRoot(), which the planner only used for storing a path to a texture pack (allowing alternate, possibly higher-resolution, textures for reactor components), which in turn was not a highly-demanded feature.

**Comment by KrisBigK** [comment]
I don't think it is likely for others to see this. Only little people knows about your git page, and less people go on here to search for bugs. Since this bug is only found here, it is more likely that this bug no longer occurs on newer versions of Java. Maybe making a FAQ page on the forum can draw more attention.
