### ISSUE TITLE
How can I open it?

### ISSUE THREAD

**Issue by fluid-uu-matter** [MauveCloud/Ic2ExpReactorPlanner#12]
I double-clicked the downloaded file,the file opens as a compressed file.

**Comment by MauveCloud** [comment]
Depends on your OS, but basically that means you either don't have Java installed, or you configured a compressed-file handler program to open it instead of Java.  Either way, not an inherent issue with my planner.
Windows: http://stackoverflow.com/questions/394616/running-jar-file-on-windows
Ubuntu: http://askubuntu.com/questions/192914/how-run-a-jar-file-with-a-double-click
I don't find a general answer for handling that issue on Mac OS.

**Comment by fluid-uu-matter** [comment]
It's a .zip file! not a jar file!

**Comment by MauveCloud** [comment]
Then your browser is probably doing something weird with the download (I just checked the releases page, and it definitely has the .jar extension there) - just rename it to have a .jar extension (turning off "Hide extensions for known file types" helps if you're using Windows and haven't already done that), and make sure your file associations allow running that via Java instead of opening it with a decompressor program.
