### ISSUE TITLE
I18n Request

### ISSUE THREAD

**Issue by xfl03** [MauveCloud/Ic2ExpReactorPlanner#13]
Dear Author,
It is a great program to plan reactor in ic2exp.
Could you add i18n feature in order to make people around this world can use it better.

**Comment by MauveCloud** [comment]
I've added support for i18n in v2.1.4, though I haven't added any translations yet, since I figure that's better left to people who know other languages better.  I know some Spanish and Japanese in addition to my first language, which is US English, but not well enough to add translations for them.

For anyone who wants to provide translations, here are some ways to send them to me, in roughly descending order of preference:
1. post in this thread: http://forum.industrial-craft.net/index.php?page=Thread&threadID=10998
2. private message on the Industrial Craft forum
3. GitHub issue with attachment
4. Pull Request
