### ISSUE TITLE
MOX cells are treated the same as uranium

### ISSUE THREAD

**Issue by bryanlyon** [MauveCloud/Ic2ExpReactorPlanner#17]
Mox cells in the planner are being treated the same as uranium cells.

- They last as long as uranium (10,000 ticks vs the correct 5,000 ticks)
- They don't gain efficiency as the heat level rises.

These problems make it difficult to see efficiency and plan a reactor for MOX cells.

**Comment by lOmicronl** [comment]
I'm pretty sure Uranium lasts 20,000s, not 10,000s. Source: I am playing with IC2 Experimental in 1.10.2 right now, and am powering my base with a nuclear reactor.

This is consistent with the planner, which treats Uranium as lasting 20,000s. Notably _not_ the same as MOX. Not sure why you're seeing Uranium at 10,000s in your planner - do you have the latest version?

**Comment by MauveCloud** [comment]
I'm fairly sure MOX cells have always lasted 10k seconds since they were added, not 5k, unless you're using some weird custom version of IC2.  I don't remember exactly what version of IC2 increased the life of Uranium cells from 10k seconds to 20k, but I'm fairly sure they've always been 20k in the experimental planner.  As far as MOX cells not gaining efficiency with heat level, perhaps you're using them in a fluid reactor, where they only double output once the reactor heat goes over 50%, rather than linearly with heat, which last I knew was consistent with how IC2 actually works.
