### ISSUE TITLE
Material list issue

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#25]
![problem](https://user-images.githubusercontent.com/34199560/33521176-aea9964a-d805-11e7-88a7-ffe52ecc5dba.png)
the iridium reinforced plate should be 4 iridim ore, 4 advanced alloy and 1 diamond.

**Comment by MauveCloud** [comment]
Okay, it seems I'll have to be more careful about wording my commits - I don't consider it appropriate to auto-close a bug from the commit - a bug should only be closed once I've actually put up a release that includes the fix.  Anyway, this is fixed now in v2.1.7.  Also, I noticed that IC2 2.3+ uses dense copper plates in the recipe, so I included that in the new materials list, but instead of "Iridium Ore" I just listed it as "Iridium" - this is partially for consistency with the other materials and partially in deference to the Iridium Neutron Reflector's GregTech origins (with GregTech installed, "Iridium Ore" becomes a little ambiguous, and the iridium needs to be made into simple plates as part of making the "Iridium Reinforced Plate", so IC2's renaming of that to just "Iridium Plate" becomes a bit confusing).
