### ISSUE TITLE
Wrong average efficiency displayed

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#28]
When I was trying to use GT5 thorium fuel rods as neutron reflectors, I found that the average efficiency was way higher than the max efficiency. idk what was wrong about it.
![problem](https://user-images.githubusercontent.com/34199560/36536585-6f01bed0-1808-11e8-948e-debcd87b29b3.PNG)

**Comment by MauveCloud** [comment]
I'm concerned about your priorities - if the reactor will overheat at 3 seconds, how much difference does it make whether the "average" efficiency reports as higher than the "maximum"?

Anyway, this is fixed in v2.1.7.1.

Also, I'm curious what design you actually simulated - the yellow highlight on an empty grid slot indicates there was a component there before that you removed, and when I tried simulating the design shown, it overheated at 21 seconds, rather than 3 seconds.

**Comment by KrisBigK** [comment]
Well, I was actually designing another reactor(001A09000C000C12001A061A0C0D0C0D0C12091A0C0D0C0D0C0D0C000C0D0C0D0C0D0C000C0D0C0D0C0D0C0D0C000C000C000C000C00). To avoid confusions, I only displayed the fuel rod part of my design and changed a little, but forgot to clear grid.(000000000000000000000000091A000000000000001A061A000000000000001A09000000000000000000000000000000000000000000), causing this. Sorry!
