### ISSUE TITLE
Minor Problem

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#30]
![minor_problem](https://user-images.githubusercontent.com/34199560/36717093-aab7d694-1bd7-11e8-86e7-788cfa085773.PNG)
In this design, there are no fuel rods at all, so heat output before fuel rods stopped should be 0.
Also, some fluid reactor designs can continue to output heat because of damaged components.

**Comment by MauveCloud** [comment]
I'm well aware that fluid reactors can keep outputting heat after being switched off (or by venting from coolant cells with no fuel rods) because of residual component heat (which I consider distinct from "damaged" components, even if Minecraft uses the same durability field/tag for it), and I discovered that the planner used the same i18n resource for that is it did for the heat outputs while the reactor was active.

**Comment by MauveCloud** [comment]
Fixed in v2.1.8
