### ISSUE TITLE
[Suggestion] Hideable inputs and threshold temperatures in component palette

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#48]
This is just to make the practical minimum window width smaller. With the inputs displaying, the width of the component palette is limited by the three input boxes. 

I would suggest adding a checkbox in the advanced tab to toggle the display of inputs/temperaturs and automatically display abbreviations of inputs (with full display when mouse is hovered on it) when the width is too small like this
![image](https://user-images.githubusercontent.com/34199560/54866923-8ce8d800-4db5-11e9-811b-db75fc50ace9.png)
By hiding the threshold temperatures, the width can be reduced further. Also, this isn't used often, so hiding it will be okay.

**Comment by MauveCloud** [comment]
After dealing with the other resizing issues, minimum window size (at least in Win10) comes out as 901x693:
![MinimumPlannerSize](https://user-images.githubusercontent.com/8942955/54871551-0c08ec80-4d73-11e9-8b09-1489d1f56dff.png)
I'm a little confused by that, since I thought I'd set the minimum size to 915x720, but I can put up with it.

Anyway, I don't see much need to abbreviate the input labels, but I'll see about adding an option to hide them.
