### ISSUE TITLE
[Suggestion] Change the default value of maximum reactor ticks to simulate based on simulations settings unless it was manually changed

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#50]
If there is no fuel rods, then set it to 5 million
If there is fuel rods, then set it to the minimum durability of the fuel rods used unless it is automated
If the reactor contains components (excluding the fuel rods) that have non-default thresholds, then set it to 5 million

**Comment by MauveCloud** [comment]
I'm not sure I see the point of this.  Maybe it isn't obvious, but the setting is to allow a user to force the simulation to stop earlier than it otherwise would.

> unless it was manually changed

That would force me to come up with a way to make the program "remember" if the user has manually changed the value, possibly to match what would otherwise be a default value.

> If there is fuel rods, then set it to the minimum durability of the fuel rods used unless it is automated

Shouldn't that be the maximum for a mixed-fuel reactor?  Also, what about a pulsed reactor?  If the pulse config is only using a clock circuit, the total time can be predicted, but not if temperature controls are set (though using temperature controls can help to find good pulse timings - with the released build, one would have to look at CSV data, but there are pending changes to make this a little easier)

**Comment by KrisBigK** [comment]
> Maybe it isn't obvious, but the setting is to allow a user to force the simulation to stop earlier than it otherwise would.

In a lot of cases, people don't need to simulate it for 5 million ticks when designing a reactor, so simply setting the default to 5 million is like overkill. Also, newbies probably won't know what is a reactor tick and the meanings of setting, so this could make it easier for them to use.

> Shouldn't that be the maximum for a mixed-fuel reactor? Also, what about a pulsed reactor?

For a mixed-fuel reactor, after the first fuel rod is depleted and not changed, less heat would be generated so that the reactor might look stable but it would explode with all rods running.

For a pulsed reactor, I think that should leave to the user to decide whether the user wants to test short or long term stability.

**Comment by MauveCloud** [comment]
> Also, newbies probably won't know what is a reactor tick and the meanings of setting, so this could make it easier for them to use.

I'm not sure how likely it is for players to find the planner without first finding out about reactor ticks, but I guess I should make my planner more consistent and show seconds instead of reactor ticks.

> In a lot of cases, people don't need to simulate it for 5 million ticks when designing a reactor

True, but for non-automated reactors, there are already other conditions for stopping the simulation, usually before it gets to 5 million ticks.  I feel like making this change in response to design changes would only lead to _more_ confusion.  I can add a tooltip to explain what the setting does, though.

**Comment by KrisBigK** [comment]
>  I feel like making this change in response to design changes would only lead to more confusion. I can add a tooltip to explain what the setting does, though.

Why more confusion? I thought that it could be more convenient. However, I agree with your tooltip idea.

**Comment by MauveCloud** [comment]
I've removed user-visible mentions of "reactor ticks" in v2.3.2, and added the tooltip.
