### ISSUE TITLE
[Suggestion] Add a button to make the window turn into default size

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#51]

**Comment by MauveCloud** [comment]
Please explain your reasons for wanting this, and what advantage it would have over closing and relaunching the planner to regain default size.

**Comment by KrisBigK** [comment]
Sorry about that. I didn't realize that it was automatically set to default after version 2.3.
One insignificant advantage though. Since you aren't willing to add a history, relaunching would loose the current design although copying it could do the work.

**Comment by MauveCloud** [comment]
> Since you aren't willing to add a history, relaunching would loose the current design although copying it could do the work.

Exactly.  Seems to me copying & pasting the reactor code into a text editor makes more sense than relying on an undo history - this way users can decide for themselves when to save designs for possible rollback, instead of using an "undo" command potentially dozens of times.

> I didn't realize that it was automatically set to default after version 2.3.

It's not a new feature, it has been that way since v1.0.  If there's enough demand for preserving a changed window size (and split-pane sizes), I'd have to do a bit of research to find how to do that.
