### ISSUE TITLE
Heating & cooling details don't show up when there is enough time to collect data

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#53]
erp=C51pU0VBfvHayfMXrK+LlqItfeTLz+9X4iUui6/dW1onq7gF7O4+/2/ALAE=
![image](https://user-images.githubusercontent.com/34199560/55067134-210ab600-50ba-11e9-943d-7703cd01c3ec.png)
> Adjusted heating and cooling details shown in simulation. (if the reactor has had at least 20 simulated seconds for components to stabilize and at least 20 more seconds to collect sufficient data, it shows average hull heating, average component heating, average and possible hull cooling, and average and possible vent cooling (if applicable))

This one explodes after 5000 sec, much longer than the time you specified to collect its data. Adding another reactor heat vent makes it stable, thus displaying those details.

**Comment by MauveCloud** [comment]
While we're at it, I noticed an inconsistency in the reported time of overheating:

> Reactor will explode at 4999 seconds.
...
Reactor overheated at 5,000 seconds.

I will fix that as well. (and I think the other thresholds would technically be reached 1 second later, though that would be difficult to verify in-game, because many of their effects happen sporadically instead of immediately like the explosion)
