### ISSUE TITLE
Threshold of invulnerable Components is (improperly) contained in the reactor code

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#60]
In v2.3.0.2, the whole threshold is in the code.
![image](https://user-images.githubusercontent.com/34199560/55079978-3f7faa00-50d8-11e9-9604-7c9b2a716bd5.png)

In v2.3.2, an extra parenthesis is still left in the code. Who can tell if it has an extra parenthesis just looking at a pile of Base-64 "nonsense"?
![image](https://user-images.githubusercontent.com/34199560/55080314-f0864480-50d8-11e9-9e13-d8ea418cf180.png)
Also, clicking on the "Show old-style reactor code" twice makes the extra parenthesis disappear again.

**Comment by MauveCloud** [comment]
I don't see the first part as that big a deal - sure, it's technically adding a little extra size to the code, but it doesn't seem worth the effort just to squeeze the reactor code just a few characters shorter.  The residual close-parenthesis I'll investigate, though.

**Comment by MauveCloud** [comment]
Okay, I've fixed the first part a little deeper - instead of just checking for them when generating the reactor code, "invulnerable" components won't even be able to have their automation thresholds or reactor pauses permanently set.  The second part had to do with inconsistent conditon checking between whether the parentheses were needed vs. whether any values were actually inserted - turning on "automated reactor" would show the whole threshold in v2.3.2.
