### ISSUE TITLE
Gigantic number

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#73]
Every time when two designs that doesn't have a heat source are compared (at least that's what I've found), a gigantic number appears in the comparison tab. (approx. 1.8*10^310)
![image](https://user-images.githubusercontent.com/34199560/56280922-dff84580-613d-11e9-9330-a3c6182c4450.png)
erp=AudaVNFQksjYfyHgGDoimAyE7JuwPqKV4eFfE+bh0n2lY9Jiik78PV1QAQ==
erp=Bc60qaKhJumZYZKO268xGvIGNTek002fIWA7LxCEi1ndjrRAXQzsiJzQAQ==

**Comment by KrisBigK** [comment]
Seems that this is still not properly fixed...
![image](https://user-images.githubusercontent.com/34199560/60716301-960b4880-9f51-11e9-84a9-7a465f40f1e2.png)

erp=G6ue47/zeoeYC6+pHMjHOQu5qqrl8YOgB23E7pNAME3UmJW9yiltCwF2sxvlxPSOPwTxubayroEpxQE=
erp=G6ue47/zeoeYC6+pHMjHOQu5qqrl8YOgB23E7pNAME3UmJW9yiltCwF2sxvlxPSOPwTxubayroEpxwE=

**Comment by MauveCloud** [comment]
The trigger for this was a bit different than the original bug, but I've added some "sanity check" conditions to make sure that the "minimum" is set below the "maximum" before showing them in comparison.

As far as exploding when automated, I looked at CSV output and discovered there was a bug with pulse timing when automation was turned on, which I think I've fixed in the next version.
